name: coding_challenge
description: A Flutter Project For a Coding Challenge
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: 8.0.3
  dio: 4.0.4
  equatable: 2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  json_annotation: 4.4.0
  retrofit: 3.0.1+1

dev_dependencies:
  build_runner: 2.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4
  json_serializable: 6.1.4
  retrofit_generator: 4.0.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
